### ISSUE TITLE
слово "нашли" ставит не в "найти", а в "наслать"

### ISSUE THREAD

**Issue by Excellents1** [no-plagiarism/pymorphy3#14]
слово "нашли" ставит не в "найти", а в "наслать"

**Comment by insolor** [comment]
Проблема не в pymorphy* как таковом, а в таком явлении как омонимия. Только по одному слову часто нельзя со 100% уверенностью определить исходную форму или даже часть речи ("стали" - это глагол или существительное?)

Часто решить можно, если брать не первый разбор, а из всех разборов выбирать подходящие. Например, если известно, что не может быть повелительного наклонения, то и оставляете результаты не в повелительном наклонении:
```
morph = MorphAnalyzer()
p = morph.parse("нашли")
print(p)
# [Parse(word='нашли', tag=OpencorporaTag('VERB,perf,tran sing,impr,excl'), normal_form='наслать', score=0.5, methods_stack=((DictionaryAnalyzer(), 'нашли', 1392, 13),)), Parse(word='нашли', tag=OpencorporaTag('VERB,perf,tran plur,past,indc'), normal_form='найти', score=0.5, methods_stack=((DictionaryAnalyzer(), 'нашли', 2096, 4),))]

# Нужно убрать все результаты где в tag есть impr - императив, он же повелительное наклонение
p = [item for item in p if "impr" not in item.tag]
print(p)
# [Parse(word='нашли', tag=OpencorporaTag('VERB,perf,tran plur,past,indc'), normal_form='найти', score=0.5, methods_stack=((DictionaryAnalyzer(), 'нашли', 2096, 4),))]
print(p[0].normal_form)
# найти

**Comment by Shimorina** [comment]
сняла неоднозначность вручную для пары таких примеров в корпусе OpenCorpora. Если завтра скачать новую версию корпуса и пересобрать словари, то score у "найти" будет выше, чем 0,5, и он будет первым разбором.

**Comment by Shimorina** [comment]
нет, просто у слова "нашли" не была снята неоднозначность в корпусе. "найти" это более частотный вариант, судя по примерам, поэтому я и сняла неоднозначность в паре случаев, теперь "найти" должен стать более частотным разбором

**Comment by snooppr** [comment]
@Shimorina 

> сняла неоднозначность вручную для пары таких примеров в корпусе OpenCorpora. Если завтра скачать новую версию корпуса и пересобрать словари, то score у "найти" будет выше, чем 0,5, и он будет первым разбором.

Можете пояснить про "неоднозначность". Пересобрал словари от 28 января 2026.
Пример1 ("наслать" так и осталось первым кандидатом):
> "найти" будет выше, чем 0,5, и он будет первым разбором.

`morph.parse("нашли")[0].normal_form`
**'наслать'**

`morph.parse("нашли")`
[Parse(word='нашли', tag=OpencorporaTag('VERB,perf,tran sing,impr,excl'), normal_form='наслать', score=1.0, methods_stack=((DictionaryAnalyzer(), 'нашли', 1392, 13),)), Parse(word='нашли', tag=OpencorporaTag('VERB,perf,tran plur,past,indc'), normal_form='найти', score=1.0, methods_stack=((DictionaryAnalyzer(), 'нашли', 2096, 4),))]

Пример2 ("Сирый" так и осталось первым кандидатом):
`morph.parse("сир")[0].normal_form`
**'сирый'**

`morph.parse("сир")`
[Parse(word='сир', tag=OpencorporaTag('ADJS,Qual masc,sing'), normal_form='сирый', score=1.0, methods_stack=((DictionaryAnalyzer(), 'сир', 4, 27),)), Parse(word='сир', tag=OpencorporaTag('NOUN,anim,masc sing,nomn'), normal_form='сир', score=1.0, methods_stack=((DictionaryAnalyzer(), 'сир', 52, 0),))]
"Сир" и "Сирый" - в НКРЯ упоминаются ~поровну в русской прозе. Однако, в средневековье всюду "Сир", как титул/обращение. Слово "сир" — никак в pytmorphy по умолчанию нельзя сделать первым кандидатом?

Упомянутая вами "неоднозначность" решает где-то в контексте текста, а не по отдельным словам, или что имели в виду?

**Comment by Shimorina** [comment]
про "нашли" это странно, что так. Точно использовалась новая версия корпуса при пересборке: https://github.com/no-plagiarism/pymorphy3-dicts/blob/master/update.py#L28?

Я еще добавила примеров, можно ещё раз попробовать завтра пересобрать словари.

Про "сир":
В корпусе нет словоформы "сир" в значении "сэр": https://opencorpora.org/search.php?q=%D1%81%D0%B8%D1%80&exact_form=0 , поэтому для пары сирый/сир всегда будет неоднозначность. В корпусе есть "Сир" как сокращение от Сиракид, могу добавить его в словарь как "NOUN,anim,masc sing,nomn,Name, Abbr". Тогда в pymorphy будут неправильные теги (name, abbr), но по крайней мере начальная формы будет "сир" и как сущ-е. Подойдет вам такой вариант?

**Comment by snooppr** [comment]
@Shimorina , вероятно, неправильно пересобрал словарь, хотя он работал: инструкции нет, readme - невалидный унаследованный, кривой, черновик, а не инструкция. Поднял историю bash,
`python build-dict.py dict.opcorpora.xml compiled-dicts --lang ru --clear`  - вероятно в этом и ошибка была, собрал только словарь, и он работал, т.к. увидел свежую словоформу: "_сир_"

Благодаря вашей подсказке понял что придётся смотреть код, но там ошибки, у пользователя будет сразу падать установка на первом же шаге (http поправил на https):
https://github.com/no-plagiarism/pymorphy3-dicts/blob/1e926cf54b327aaedfb4fd8e67ede31e69487a61/update.py#L27-L28

`python update.py ru download compile` - к сожалению на одном python3.12 прошло все гладко, на другом падения после компиляции словаря и обработке вот его "annot.corpus.xml".
err:
```
Reading disambiguated words from corpus: 1532404it [05:41, 4480.80it/s]
Filtering out non-ambiguous words:   0%| | 0/1532404 [00:00Traceback (most recent call last):
  File "./build-dict.py", line 102, in <module>
    add_conditional_tag_probability(
  File "/data/data/com.termux/files/home/.local/share/virtualenvs/pymorphy3-dicts-sb3OHjCk/lib/python3.8/site-packages/pymorphy3/opencorpora_dict/probability.py", line 29, in add_conditional_tag_probability
    cpd, cfd = estimate_conditional_tag_probability(morph, corpus_filename, logger)
  File "/data/data/com.termux/files/home/.local/share/virtualenvs/pymorphy3-dicts-sb3OHjCk/lib/python3.8/site-packages/pymorphy3/opencorpora_dict/probability.py", line 80, in estimate_conditional_tag_probability
    ambiguous_words = [
  File "/data/data/com.termux/files/home/.local/share/virtualenvs/pymorphy3-dicts-sb3OHjCk/lib/python3.8/site-packages/pymorphy3/opencorpora_dict/probability.py", line 80, in <listcomp>
    ambiguous_words = [
  File "/data/data/com.termux/files/home/.local/share/virtualenvs/pymorphy3-dicts-sb3OHjCk/lib/python3.8/site-packages/pymorphy3/opencorpora_dict/probability.py", line 84, in <genexpr>
    if len(morph.tag(w)) > 1
  File "/data/data/com.termux/files/home/.local/share/virtualenvs/pymorphy3-dicts-sb3OHjCk/lib/python3.8/site-packages/pymorphy3/analyzer.py", line 350, in tag
    res.extend(analyzer.tag(word, word_lower, seen))
  File "/data/data/com.termux/files/home/.local/share/virtualenvs/pymorphy3-dicts-sb3OHjCk/lib/python3.8/site-packages/pymorphy3/units/by_lookup.py", line 41, in tag
    para_data = self.dict.words.similar_item_values(word_lower, self.morph.char_substitutes)
  File "src/dawg.pyx", line 793, in dawg.BytesDAWG.similar_item_values
  File "src/dawg.pyx", line 803, in dawg.BytesDAWG.similar_item_values
  File "src/dawg.pyx", line 788, in dawg.BytesDAWG._similar_item_values
  File "src/dawg.pyx", line 844, in dawg.RecordDAWG._value_for_index
struct.error: unpack requires a buffer of 4 bytes
Filtering out non-ambiguous words:
```

----------

Там, где изначально компилировал без "annot.corpus.xml" - он влияет именно на выходной словарь? Словарь работал, но слова чудили.
С "annot.corpus.xml" пересобрал — корректнее/логичнее многие слова стали, например, "нашли" - > "найти", "спина" - > "спина", а не "спин", как было. Правда слово "венам" выдает: "вено", а не "вена" - его нельзя поправить в корпусе, "вена" вроде более популярная лексема, чем "вено".

**Comment by Shimorina** [comment]
здорово, что в итоге получилось обновить :)

pymorphy3-dicts строятся на двух компонентах из OpenCorpora: словаре (dict.opcorpora.xml) и корпусе (annot.corpus.xml). Из словаря берутся лексемы со словоформами, а по корпусу подсчитывается score статистика --- какая начальная форма более частотна для определенной словоформы (например, найти/наслать для "нашли").

для словоформы "венам" такой же ответ, как и про "сир", такой словоформы сейчас в корпусе нет (https://opencorpora.org/search.php?q=%D0%B2%D0%B5%D0%BD%D0%B0%D0%BC), поэтому статистики для нее не посчитать к сожалению. Статистика считается по словоформам ("венам"), а не по лексемам ("вена"/"вено").
