### ISSUE TITLE
Python 3.11 compatibility

### ISSUE THREAD

**Issue by adrianeboyd** [no-plagiarism/pymorphy3#2]
It looks like pymorphy3 (and also pymorphy2) are not compatible with python 3.11.

```python
from pymorphy3 import MorphAnalyzer
morph = MorphAnalyzer(lang="uk")
```

Traceback:

```
Traceback (most recent call last):
  File "/tmp/u.py", line 2, in <module>
    morph = MorphAnalyzer(lang="uk")
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/venv311-1/lib/python3.11/site-packages/pymorphy3/analyzer.py", line 224, in __init__
    self._init_units(units)
  File "/tmp/venv311-1/lib/python3.11/site-packages/pymorphy3/analyzer.py", line 235, in _init_units
    self._units.append((self._bound_unit(unit), False))
                        ^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/venv311-1/lib/python3.11/site-packages/pymorphy3/analyzer.py", line 246, in _bound_unit
    unit = unit.clone()
           ^^^^^^^^^^^^
  File "/tmp/venv311-1/lib/python3.11/site-packages/pymorphy3/units/base.py", line 35, in clone
    return self.__class__(**self._get_params())
                            ^^^^^^^^^^^^^^^^^^
  File "/tmp/venv311-1/lib/python3.11/site-packages/pymorphy3/units/base.py", line 76, in _get_params
    (key, getattr(self, key, None)) for key in self._get_param_names()
                                               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/venv311-1/lib/python3.11/site-packages/pymorphy3/units/base.py", line 70, in _get_param_names
    args, varargs, kw, default = inspect.getargspec(cls.__init__)
                                 ^^^^^^^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?
```

**Comment by Vuizur** [comment]
It has apparently been fixed [here](https://github.com/kmike/pymorphy2/pull/157), now it only needs to be merged somewhere (for the original pymorphy2 repo the chances seem to be low).
